# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "taskmapper-trac"
  s.version = "0.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rafael George"]
  s.date = "2013-04-16"
  s.description = "Allows taskmapper to interact with Your System."
  s.email = "rafael@hybridgroup.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".rbenv-gemsets",
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/provider/comment.rb",
    "lib/provider/project.rb",
    "lib/provider/ticket.rb",
    "lib/provider/trac.rb",
    "lib/taskmapper-trac.rb",
    "lib/trac/trac.rb",
    "spec/comments_spec.rb",
    "spec/commentutil_spec.rb",
    "spec/commentutils-data.html",
    "spec/fixtures/tickets.xml",
    "spec/projects_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/taskmapper-trac_spec.rb",
    "spec/tickets_spec.rb",
    "taskmapper-trac.gemspec"
  ]
  s.homepage = "http://github.com/hybridgroup/taskmapper-trac"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "taskmapper Provider for Trac"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<taskmapper>, [">= 0"])
      s.add_runtime_dependency(%q<trac4r>, ["~> 1.2"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.5"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.5"])
      s.add_development_dependency(%q<rcov>, ["~> 1.0"])
      s.add_runtime_dependency(%q<trac4r>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<taskmapper>, [">= 0"])
      s.add_dependency(%q<trac4r>, ["~> 1.2"])
      s.add_dependency(%q<nokogiri>, ["~> 1.5"])
      s.add_dependency(%q<bundler>, ["~> 1.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_dependency(%q<simplecov>, ["~> 0.5"])
      s.add_dependency(%q<rcov>, ["~> 1.0"])
      s.add_dependency(%q<trac4r>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<taskmapper>, [">= 0"])
    s.add_dependency(%q<trac4r>, ["~> 1.2"])
    s.add_dependency(%q<nokogiri>, ["~> 1.5"])
    s.add_dependency(%q<bundler>, ["~> 1.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.6"])
    s.add_dependency(%q<simplecov>, ["~> 0.5"])
    s.add_dependency(%q<rcov>, ["~> 1.0"])
    s.add_dependency(%q<trac4r>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

